### ISSUE TITLE
Programming (reimplementation)

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-jlrzarcor#4]
- [ ] Al concluir el perfilamiento, evaluar en equipo qué se utilizará para hacer más eficiente nuestros métodos (al menos una de las siguientes):
          * Uso de niveles 2 o 3 de BLAS (preferiblemente nivel 3 de BLAS).
          * Uso de compilación a C para secciones de su código.
          * Cómputo en paralelo.
          * Cómputo concurrente.
          * Cómputo distribuido.
- [ ] Reimplementación / adición / eliminación de secciones al código de acuerdo al perfilamiento realizado.
- [ ] Añadir referencias utilizadas para la reimplementación / adición / eliminación de las secciones de su código (papers o páginas para realizar compilación a C o cómputo en paralelo incluirlas en el README.md o directamente el paper).

**Comment by jlrzarcor** [comment]
** FEEDBACK **

@Carlosrlpzi 

Hemos llegado a la conclusión de que existe un posible Bug en el código que implementamos que debemos eliminar debido a que la ruta óptima no es seleccionada. Independientemente de que nuestro código original sea más lento, buscaremos modificar el algoritmo para que sea consistente con las soluciones reportadas por [OR tools](https://developers.google.com/optimization/routing/tsp) y [python-tsp](https://github.com/fillipe-gsm/python-tsp) y solucionarlo con cómputo en paralelo.

Se relaciona con #3 .

**Comment by jlrzarcor** [comment]
@Carlosrlpzi , Charly, me ayudas porfa a integrar un cambio menor en nuestro método de Hill Climbing, simplemente la ruta imprima tanto el punto final como el inicial, esto implica que vas a tener 11 nodos  (ciudades) en los cuales el primero y el último son el mimos.

**Comment by Carlosrlpzi** [comment]
@jlrzarcor listo ya quedo. Cualquier cosa me avisas
