### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-jlrzarcor#5]
- [x] Crear nuevos tests para la reimplementación / adición / eliminación de secciones al código.
- [x] Reutilizar/mejorar el Autograding. Los tests deben pasar automáticamente (ante las reimplementaciones a realizar en nuestro paquete) con un lanzamiento de un workflow de github vía github actions.

**Comment by Lobolc** [comment]
1. Se realizó un test haciendo uso de numba.
2. Se realizó test comparando distancia obtenida con la función best_solution y la obtenida con google_tools_tsb.
