### ISSUE TITLE
Dockering

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-jlrzarcor#6]
- [x]  Crear Dockerfiles.
- [x]  Actualizar el contenedor de docker mediante github actions.
- [x]  Instalar en el contenedor el paquete trabajado por el equipo de programación.
- [x]  Reflejar automáticamente con github actions en la imágen los cambios por el equipo de reimplementación derivados del perfilamiento.

> * Nota: esta imágen debe construirse y alojarse (Build & Push) automáticamente en dockerhub con un lanzamiento de un workflow de github vía github actions. De esta forma, cualquier commit que modifique el Dockerfile debe lanzar un worfklow de github que dispare un build & push al dockerhub de manera automática.

**Comment by Lobolc** [comment]
Se creó el Dockerfile y el push and build.
